/* LEWS Surveyor's Field Console: operational clarity, cartographic texture, calm urgency. */
import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Check, ChevronDown, ChevronRight, CloudRain, Crosshair, Gauge, Layers3, MapPin, Radio, RotateCcw, Send, ShieldAlert, Siren, Sprout, Waves, Wind, X } from "lucide-react";

type Tier = "STABLE" | "WATCH" | "CRITICAL";
type Zone = { id:string; name:string; region:string; coords:string; rainfall:number; soil:number; tilt:number; baseline:number; sensors:number; history:number[]; tier:Tier; score:number; sensitivity:{rain:number; soil:number; tilt:number} };
type AlertEvent = { time:string; zone:string; transition:string; risk:number };

const initialZones: Zone[] = [
  {id:"CHK-01",name:"Chikkamagaluru",region:"Western Ghats",coords:"13.3153, 75.7754",rainfall:12.8,soil:57.4,tilt:0.062,baseline:31,sensors:10,history:[31,32,32,33,32,34,35,34,35,36,35,36],tier:"STABLE",score:35,sensitivity:{rain:0.9,soil:0.85,tilt:0.8}},
  {id:"KDG-03",name:"Kodagu",region:"Western Ghats",coords:"12.3375, 75.8069",rainfall:18.4,soil:78.2,tilt:0.084,baseline:42,sensors:12,history:[52,55,56,58,57,60,59,61,62,60,63,64],tier:"WATCH",score:64,sensitivity:{rain:1.15,soil:1.12,tilt:0.9}},
  {id:"UKA-02",name:"Uttara Kannada",region:"Western Ghats",coords:"14.7937, 74.6869",rainfall:9.6,soil:49.8,tilt:0.057,baseline:28,sensors:9,history:[28,29,30,29,31,30,30,31,32,31,31,32],tier:"STABLE",score:32,sensitivity:{rain:0.92,soil:0.86,tilt:0.82}},
  {id:"WYD-04",name:"Wayanad",region:"Western Ghats",coords:"11.6854, 76.1320",rainfall:15.1,soil:71.4,tilt:0.068,baseline:37,sensors:11,history:[43,44,45,44,46,47,48,47,49,48,49,50],tier:"WATCH",score:50,sensitivity:{rain:0.92,soil:1.18,tilt:0.86}},
  {id:"NLG-05",name:"Nilgiris",region:"Tamil Nadu",coords:"11.4102, 76.6950",rainfall:11.2,soil:53.6,tilt:0.092,baseline:39,sensors:8,history:[41,42,41,43,44,43,45,44,46,45,47,48],tier:"WATCH",score:48,sensitivity:{rain:0.88,soil:0.9,tilt:1.2}},
  {id:"DJE-06",name:"Darjeeling",region:"Eastern Himalayas",coords:"27.0410, 88.2663",rainfall:13.5,soil:61.7,tilt:0.101,baseline:44,sensors:13,history:[50,51,52,51,53,54,53,55,54,56,55,57],tier:"WATCH",score:57,sensitivity:{rain:0.9,soil:0.94,tilt:1.22}},
];

const statusColor = (tier:Tier) => tier === "CRITICAL" ? "#C24B3F" : tier === "WATCH" ? "#D6A24E" : "#6FA377";
const classify = (score:number):Tier => score >= 71 ? "CRITICAL" : score >= 40 ? "WATCH" : "STABLE";
const clock = () => new Date().toLocaleTimeString("en-GB", {hour12:false});

function calcScore(z:Zone) {
  const rain = Math.min(100, (z.rainfall / 32) * 100) * z.sensitivity.rain;
  const soil = Math.min(100, z.soil) * z.sensitivity.soil;
  const tilt = Math.min(100, (z.tilt / 0.16) * 100) * z.sensitivity.tilt;
  return Math.max(0, Math.min(100, Math.round(0.4 * rain + 0.35 * soil + 0.25 * tilt + z.baseline * 0.08)));
}
function delta(a:number,b:number) { const d = a-b; return `${d >= 0 ? "+" : ""}${d.toFixed(1)}`; }
function TinySpark({values,color}:{values:number[];color:string}) { const min=Math.min(...values), max=Math.max(...values); const points=values.map((v,i)=>`${(i/(values.length-1))*100},${34-((v-min)/Math.max(1,max-min))*24}`).join(" "); const current=Math.round(values[values.length-1]); return <svg className="spark" viewBox="0 0 100 40" preserveAspectRatio="none" aria-label={`Risk trend ending at ${current} out of 100`}><text className="spark-number" x="98" y="29" textAnchor="end">{current}</text><polyline points={points} fill="none" stroke={color} strokeWidth="3" vectorEffect="non-scaling-stroke" /></svg> }
function TrendChart({values,tier}:{values:number[];tier:Tier}) { const points=values.map((v,i)=>`${(i/(values.length-1))*100},${100-v}`).join(" "); return <div className="trend-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor={statusColor(tier)} stopOpacity=".22"/><stop offset="1" stopColor={statusColor(tier)} stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#chartFill)"/><polyline points={points} fill="none" stroke={statusColor(tier)} strokeWidth="2.2" vectorEffect="non-scaling-stroke" /></svg><div className="chart-labels"><span>−16 READINGS</span><span>NOW</span></div></div> }

export default function Home() {
  const [zones,setZones] = useState(initialZones); const [selected,setSelected] = useState("KDG-03"); const [events,setEvents] = useState<AlertEvent[]>([]); const [lastUpdate,setLastUpdate] = useState(clock()); const [scenario,setScenario] = useState("NORMAL DAY"); const [storm,setStorm] = useState(false); const [stormProgress,setStormProgress] = useState(0); const [ack,setAck] = useState(false); const [notice,setNotice] = useState<string | null>(null); const [profile,setProfile] = useState(false); const timer=useRef<number | undefined>(undefined);
  const zone = zones.find(z=>z.id===selected) || zones[1];
  const maxTier = useMemo(()=>zones.some(z=>z.tier==="CRITICAL")?"CRITICAL":zones.some(z=>z.tier==="WATCH")?"WATCH":"STABLE",[zones]);

  useEffect(()=>{ timer.current=window.setInterval(()=>{ setZones(prev=>prev.map(z=>{ const oldTier=z.tier; const stormBoost=storm ? stormProgress/100 : 0; const intensity=scenario==="HEAVY RAIN" ? 1.55 : scenario==="EXTREME SLOPE EVENT" ? 1.8 : 1; const rain=Math.max(2,Math.min(34,z.rainfall + (Math.random()-.46)*intensity + stormBoost*1.25)); const soil=Math.max(25,Math.min(94,z.soil + (rain>z.rainfall?.16:-.08)*intensity + (Math.random()-.52)*.45 + stormBoost*.28)); const tilt=Math.max(.025,Math.min(.145,z.tilt + (Math.random()-.47)*.002*intensity + stormBoost*.0009)); const next={...z,rainfall:Number(rain.toFixed(1)),soil:Number(soil.toFixed(1)),tilt:Number(tilt.toFixed(3))}; const score=calcScore(next); const tier=classify(score); if(tier!==oldTier){ setEvents(es=>[{time:clock(),zone:z.name,transition:`${oldTier} → ${tier}`,risk:score},...es].slice(0,6)); } return {...next,score,tier,history:[...z.history.slice(-15),score]}; })); setLastUpdate(clock()); },2500); return ()=>window.clearInterval(timer.current); },[scenario,storm,stormProgress]);
  useEffect(()=>{ if(storm && stormProgress<100){ const t=window.setTimeout(()=>setStormProgress(p=>Math.min(100,p+6)),1000); return ()=>window.clearTimeout(t); } if(stormProgress>=100) setStorm(false); },[storm,stormProgress]);
  const reset=()=>{setZones(initialZones);setEvents([]);setStorm(false);setStormProgress(0);setScenario("NORMAL DAY");setNotice("Simulation reset to baseline conditions.");};
  const runStorm=()=>{setSelected("KDG-03");setScenario("EXTREME SLOPE EVENT");setStormProgress(0);setStorm(true);setAck(false);setNotice("Storm scenario initiated — escalation timeline active.");};
  const setPreset=(name:string)=>{setScenario(name);setStorm(name!=="NORMAL DAY");setStormProgress(name==="NORMAL DAY"?0:25);setNotice(`${name} preset loaded.`);};
  const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
  const contributions={rain:Math.round(Math.min(100,zone.rainfall/32*100)*zone.sensitivity.rain),soil:Math.round(zone.soil*zone.sensitivity.soil),tilt:Math.round(Math.min(100,zone.tilt/.16*100)*zone.sensitivity.tilt)}; const total=contributions.rain+contributions.soil+contributions.tilt;
  const reason=contributions.rain>=contributions.soil&&contributions.rain>=contributions.tilt?"Rainfall intensity is currently the strongest contributor.":contributions.soil>=contributions.tilt?"Soil moisture is approaching saturation for this zone.":"Slope tilt is increasing above the local baseline.";

  return <div className="app-shell"><aside className="instrument-rail"><div className="rail-mark"><img src="/manus-storage/lews-logo_09575f20.png" alt="LEWS contour ridge mark"/></div><span className="rail-line"/><span className="rail-index">00<br/><i/>05</span><div className="rail-meta">FIELD<br/>CONSOLE<br/><b>13° N</b><br/><b>75° E</b></div></aside>
    <header className="topbar"><a className="brand" href="#top"><div className="logo-wrap"><img src="/manus-storage/lews-logo_09575f20.png" alt="LEWS contour ridge mark" /></div><div><div className="brand-name">LEWS</div><div className="brand-sub">LANDSLIDE EARLY WARNING SYSTEM</div></div></a><nav><a href="#top">Home</a><a href="#dashboard">Live Dashboard</a><a href="#how">How It Works</a><a href="#about">About</a></nav><div className="online"><span className="status-dot stable-dot"/> SYSTEM ONLINE <small>LEWS v0.1</small></div></header>
    <main id="top">
      <section className="hero"><div className="hero-art"/><div className="hero-copy"><div className="eyebrow"><span className="rule"/> HYPERLOCAL MONITORING / PROTOTYPE</div><h1>Warning before<br/><em>the bulletin.</em></h1><p className="hero-lead">LEWS demonstrates a hyperlocal last-mile warning layer combining slope monitoring, explainable risk scoring and evacuation-ready response information for a specific hillside or village.</p><div className="hero-actions"><button className="button primary" onClick={()=>scroll("dashboard")}>VIEW LIVE DASHBOARD <ChevronRight size={16}/></button><button className="button secondary" onClick={()=>scroll("how")}>HOW IT WORKS <span className="arrow">↓</span></button></div><div className="hero-note"><span>REAL SYSTEM BEHAVIOR</span><span className="slash">/</span><span>SIMULATED SENSOR INPUTS</span></div></div><div className="hero-coords">13°18'55.1" N<br/>75°48'24.8" E<br/><span>FIELD NODE / 06</span><br/><small>CONTOUR INTERVAL / 20M</small></div></section>
      <section className="stat-strip"><div><strong>12.6%</strong><span>of India's land area is<br/>landslide-prone</span></div><div><strong>21</strong><span>districts under GSI<br/>regional bulletins</span></div><div><strong>06</strong><span>zones monitored by<br/>this prototype</span></div><p>REFERENCE: GSI / NDMA<br/>PUBLIC SOURCES</p></section>
      <section id="dashboard" className="dashboard-section"><div className="section-heading"><div><div className="eyebrow"><span className="rule"/> OPERATIONS VIEW / 01</div><h2>Live slope monitoring</h2></div><div className="dash-meta"><span className="live-pill"><i/> SYSTEM ONLINE</span><span className="sim-label">SIMULATED DATA</span><span>UPDATE INTERVAL: 2.5s</span><span>LAST UPDATE: {lastUpdate}</span></div></div><div className="warning"><AlertTriangle size={15}/> SIMULATION MODE — Sensor readings shown here are simulated for prototype demonstration and do not represent real-time field measurements.</div>
        <div className="dashboard-grid"><aside className="zone-monitor panel"><div className="panel-title"><span>ZONE MONITOR</span><span className="mono">06 / 06</span></div><div className="zone-list">{zones.map(z=><button key={z.id} className={`zone-row ${z.id===selected?"selected":""}`} onClick={()=>setSelected(z.id)}><div className="zone-info"><div className="zone-top"><span className="status-dot" style={{background:statusColor(z.tier)}}/><strong>{z.name}</strong><span className="zone-arrow">{z.score>=z.history[z.history.length-2]?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>}</span></div><div className="zone-bottom"><span>{z.region.toUpperCase()}</span><b style={{color:statusColor(z.tier)}}>{z.tier}</b><span className="score">{z.score} / 100</span></div></div><div className="zone-spark-col"><TinySpark values={z.history} color={statusColor(z.tier)}/><span>RISK TRACE</span></div></button>)}</div><div className="network"><div className="panel-title">SENSOR NETWORK <span className="online-mini"><i/> NOMINAL</span></div><div className="network-big">12 / 12 <span>CHANNELS ONLINE</span></div><div className="network-row"><span>DATA LINK</span><b>SIMULATED</b></div><div className="network-row"><span>LATENCY</span><b>1.8 SEC</b></div><div className="network-row"><span>PACKET SUCCESS</span><b>99.2%</b></div></div></aside>
          <div className="map-panel panel"><div className="map-head"><div><span className="panel-kicker">LIVE MAP / TERRAIN LAYER</span><h3>Monitored slope zones</h3></div><span className="map-mode"><Layers3 size={14}/> SIMULATION MODE</span></div><div className="map-canvas"><img src="/manus-storage/lews-contour-texture_449ff2cc.png" alt="Subtle topographic contour texture"/><div className="map-grid"/><div className="map-label label-west">WESTERN GHATS</div><div className="map-label label-east">EASTERN HIMALAYAS</div>{zones.map((z,i)=>{const positions=[[28,51],[34,62],[23,43],[31,74],[46,57],[75,31]][i]; return <button key={z.id} className={`marker ${z.id===selected?"active":""}`} style={{left:`${positions[0]}%`,top:`${positions[1]}%`,color:statusColor(z.tier)}} onClick={()=>setSelected(z.id)}><span className="marker-pulse"/><span className="marker-core"/><label>{z.name.toUpperCase()}</label></button>})}<div className="map-scale"><span>0</span><i/><span>100 km</span></div><div className="map-legend"><span><i style={{background:"#6FA377"}}/> STABLE</span><span><i style={{background:"#D6A24E"}}/> WATCH</span><span><i style={{background:"#C24B3F"}}/> CRITICAL</span></div></div><div className="map-foot"><span><Crosshair size={14}/> SELECTED: <b>{zone.id}</b></span><span>BASEMAP: TOPOGRAPHIC / DARK</span></div></div>
          <aside className="intelligence panel"><div className="panel-title"><span>ZONE INTELLIGENCE</span><span className="mono">{zone.id}</span></div><div className="selected-zone"><span>SELECTED ZONE</span><h3>{zone.name}</h3><p>{zone.region} · {zone.coords}</p></div><div className="risk-block"><div className="risk-label"><span>RISK SCORE</span><span style={{color:statusColor(zone.tier)}}>{zone.tier}</span></div><div className="gauge"><div className="gauge-track"><div className="gauge-fill" style={{width:`${zone.score}%`,background:statusColor(zone.tier)}}/></div><div className="gauge-number">{zone.score}<small>/100</small></div></div><div className="advisory" style={{borderColor:statusColor(zone.tier)}}><span>ADVISORY</span><p>{zone.tier==="STABLE"?"Conditions remain within the current monitoring baseline.":zone.tier==="WATCH"?"Elevated conditions detected. Continue enhanced monitoring and prepare for possible escalation.":"Critical conditions detected. Authority assessment and response procedures should be initiated."}</p></div></div><div className="metric-grid"><Metric icon={<CloudRain size={15}/>} label="RAINFALL" value={zone.rainfall.toFixed(1)} unit="mm/hr" prev={zone.rainfall-(zone.score%3+.2)} color="#84A6A0"/><Metric icon={<Waves size={15}/>} label="SOIL MOISTURE" value={zone.soil.toFixed(1)} unit="%" prev={zone.soil-(zone.score%2+.5)} color="#D6A24E"/><Metric icon={<Wind size={15}/>} label="SLOPE TILT" value={zone.tilt.toFixed(3)} unit="°/hr" prev={zone.tilt-.002} color="#C28A70"/></div><button className="profile-toggle" onClick={()=>setProfile(!profile)}>ZONE PROFILE <ChevronDown size={15} className={profile?"rotate":""}/></button>{profile&&<div className="profile"><span>ZONE ID <b>{zone.id}</b></span><span>SENSORS <b>{zone.sensors}</b></span><span>BASELINE RISK <b>{zone.baseline}</b></span><span>DATA SOURCE <b>SIMULATED</b></span></div>}</aside>
        </div>
        <div className="lower-grid"><div className="chart-panel panel"><div className="panel-title"><span>RISK SCORE — LAST 16 READINGS</span><span className="trend"><ArrowUpRight size={14}/> TREND {delta(zone.score,zone.history[zone.history.length-2])}</span></div><TrendChart values={zone.history} tier={zone.tier}/><div className="chart-stats"><span>CURRENT <b>{zone.score}</b></span><span>PREVIOUS <b>{zone.history[zone.history.length-2]}</b></span><span>RECENT HIGH <b>{Math.max(...zone.history)}</b></span><span>STATUS <b style={{color:statusColor(zone.tier)}}>{zone.tier}</b></span></div></div><div className="explain panel"><div className="panel-title"><span>WHY THIS SCORE?</span><span className="mono">PROTOTYPE RISK CONTRIBUTION</span></div><p>Risk is <b style={{color:statusColor(zone.tier)}}>{zone.tier}</b> because:</p><ul><li>{reason}</li><li>{zone.soil>70?"Moisture is elevated relative to baseline.":"Moisture remains below saturation threshold."}</li><li>{zone.tilt>.08?"Tilt signal is above local baseline.":"Tilt is within normal drift range."}</li></ul><div className="contributions">{[["RAINFALL",contributions.rain,"#84A6A0"],["SOIL MOISTURE",contributions.soil,"#D6A24E"],["SLOPE TILT",contributions.tilt,"#C28A70"]].map(([label,val,color])=><div className="contrib" key={label as string}><span>{label as string}<b>{Math.round((val as number)/total*100)}%</b></span><i><em style={{width:`${(val as number)/total*100}%`,background:color as string}}/></i></div>)}</div></div><div className="history panel"><div className="panel-title"><span>SENSOR HISTORY</span><span className="mono">LAST 10</span></div><div className="history-head"><span>TIME</span><span>RAIN</span><span>MOISTURE</span><span>TILT</span></div>{zone.history.slice(-5).reverse().map((v,i)=><div className="history-row" key={`${v}-${i}`}><span>{i===0?lastUpdate:`${lastUpdate.slice(0,5)}:${String(Math.max(0,38-i*2)).padStart(2,"0")}`}</span><span>{(zone.rainfall-(4-i)*.7).toFixed(1)}</span><span>{(zone.soil-(4-i)*1.1).toFixed(1)}%</span><span>{(zone.tilt-(4-i)*.002).toFixed(3)}</span></div>)}</div></div>
      </section>
      <section className="scenario-section"><div className="section-stamp">LEWS / SCN-02<br/>CONTROLLED EVENT<br/><span>SIMULATION ONLY</span></div><div className="scenario-copy"><div className="eyebrow"><span className="rule"/> DEMONSTRATION CONTROL / 02</div><h2>Make the risk<br/><em>change.</em></h2><p>Run a controlled escalation to demonstrate how sensor drift, risk classification, explainability and alert transitions connect in one operating loop.</p><button className="button storm" onClick={runStorm}><Siren size={16}/> RUN STORM SCENARIO</button>{storm&&<div className="progress-wrap"><div><span>SCENARIO ESCALATION</span><b>T+{Math.round(stormProgress/5)}s / 20s</b></div><i><em style={{width:`${stormProgress}%`}}/></i></div>}</div><div className="scenario-controls panel"><div className="panel-title"><span>SCENARIO PRESETS</span><span className="mono">{scenario}</span></div><div className="preset-grid"><button onClick={()=>setPreset("NORMAL DAY")} className={scenario==="NORMAL DAY"?"chosen":""}><Sprout size={18}/><span>NORMAL DAY<small>Stable gradual movement</small></span></button><button onClick={()=>setPreset("HEAVY RAIN")} className={scenario==="HEAVY RAIN"?"chosen":""}><CloudRain size={18}/><span>HEAVY RAIN<small>Rainfall rises first</small></span></button><button onClick={()=>setPreset("EXTREME SLOPE EVENT")} className={scenario==="EXTREME SLOPE EVENT"?"chosen":""}><Wind size={18}/><span>EXTREME SLOPE EVENT<small>All variables increase</small></span></button><button onClick={reset}><RotateCcw size={18}/><span>RESET SIMULATION<small>Return to baseline</small></span></button></div><div className="timeline"><span className="timeline-title">SCENARIO TIMELINE</span>{[["T+00:00","NORMAL CONDITIONS"],["T+00:05","RAINFALL INCREASING"],["T+00:09","SOIL MOISTURE RISING"],["T+00:12","WATCH THRESHOLD CROSSED"],["T+00:17","CRITICAL THRESHOLD CROSSED"],["T+00:18","ALERT ENGINE ACTIVATED"]].map(([time,label],i)=><div className={stormProgress>i*19?"done":""} key={time}><span>{time}</span><b>{label}</b></div>)}</div></div></section>
      <section className="response-section"><div className="alert-log panel"><div className="panel-title"><span>ALERT EVENT LOG</span><span className="mono">TIER TRANSITIONS ONLY</span></div>{events.length===0?<div className="empty-log"><Bell size={18}/><span>No tier transitions recorded.<small>Alerts appear when a zone crosses a risk threshold.</small></span></div>:events.map((e,i)=><div className="event" key={`${e.time}-${i}`}><time>{e.time}</time><div><b>{e.zone.toUpperCase()}</b><span>{e.transition}</span></div><strong style={{color:e.transition.includes("CRITICAL")?"#C24B3F":"#D6A24E"}}>RISK {e.risk}</strong></div>)}</div><div className={`critical-card panel ${maxTier==="CRITICAL"?"is-critical":""}`}><div className="panel-title"><span><ShieldAlert size={15}/> CRITICAL ALERT EXPERIENCE</span><span className="mono">{ack?"ACKNOWLEDGED":"PENDING"}</span></div>{maxTier==="CRITICAL"?<><div className="critical-content"><span>⚠ CRITICAL SLOPE CONDITION</span><h3>{zone.name}</h3><p>ZONE {zone.id} · RISK {zone.score} / 100</p><b>Authority attention recommended.</b></div><div className="critical-actions"><button className="button primary" onClick={()=>setAck(true)}>{ack?<><Check size={15}/> ALERT ACKNOWLEDGED</>:<>ACKNOWLEDGE ALERT</>}</button><button className="button secondary" onClick={()=>setNotice("Response protocol opened for demonstration.")}>VIEW RESPONSE PROTOCOL</button></div></>:<div className="empty-log"><Gauge size={18}/><span>Critical state not active.<small>Run the storm scenario to exercise the escalation path.</small></span></div>}</div></section>
      <section id="how" className="how-section"><div className="section-coordinate">SYSTEM TRACE / 04.18.26 · 13.3153 N / 75.7754 E</div><div className="section-heading"><div><div className="eyebrow"><span className="rule"/> SYSTEM LOGIC / 03</div><h2>From slope to warning</h2></div><p>One transparent chain from simulated measurement to response information.</p></div><div className="flow-cards">{[["01","SENSE","Rainfall, soil moisture and slope sensors generate measurements.",<Radio/>],["02","ANALYZE","The risk engine combines measurements with baseline terrain characteristics.",<Activity/>],["03","EXPLAIN","The system identifies the measurements contributing most to current risk.",<Gauge/>],["04","ALERT","Authorities are notified first, followed by response information when appropriate.",<Bell/>]].map(([num,title,copy,icon])=><div className="flow-card" key={num as string}><span>{num as string}</span><div className="flow-icon">{icon}</div><h3>{title as string}</h3><p>{copy as string}</p>{num!=="04"&&<ChevronRight className="flow-arrow" size={17}/>}</div>)}</div><div className="architecture"><span>SIMULATED SENSOR ENGINE</span><ChevronDown/><span>DATA INGESTION</span><ChevronDown/><span>RISK ENGINE</span><ChevronDown/><span>EXPLANATION</span><ChevronDown/><span>ALERT ENGINE</span><ChevronDown/><span>DASHBOARD</span></div></section>
      <section id="about" className="about-section"><div className="about-stamp">GSI / NDMA<br/>REFERENCE LAYER<br/><span>PUBLIC SOURCES</span></div><div className="about-image"><img src="/manus-storage/lews-slope-detail_abd7f595.png" alt="Rain-darkened monitored hillside"/><span>FIELD REFERENCE / WESTERN GHATS</span></div><div className="about-copy"><div className="eyebrow"><span className="rule"/> CONTEXT / 04</div><h2>A last-mile layer,<br/><em>not a replacement.</em></h2><p>India's Geological Survey provides regional landslide forecasting and monitoring information. LEWS explores how a hyperlocal layer could complement these systems by monitoring specific vulnerable zones.</p><div className="compare"><div><span>REGIONAL FORECASTING</span><p>Broad geographic area<br/>District / regional scale<br/>Useful for large-area awareness<br/>Limited individual-slope specificity</p></div><div className="compare-lews"><span>LEWS PROTOTYPE</span><p>Hyperlocal zones<br/>Continuous sensor stream<br/>Risk scoring and explainable factors<br/>Response-oriented information</p></div></div><blockquote>LEWS does not replace existing forecasting. It demonstrates a potential hyperlocal last-mile layer.</blockquote></div></section>
      <section className="admin-section panel"><div className="section-coordinate">NOTIFY / DEMO-ONLY · API STATUS / OFFLINE</div><div><div className="eyebrow"><span className="rule"/> DEMO NOTIFICATIONS / 05</div><h2>Notification center</h2><p>External notifications are not configured in this static prototype. Actions below remain in demo mode and do not contact real recipients.</p></div><div className="notify-state"><span className="notification-line"><Check size={14}/> DASHBOARD ALERT <b>{events.length?"TRIGGERED":"STANDBY"}</b></span><span className="notification-line"><Send size={14}/> SMS <b>DEMO QUEUED</b></span><span className="notification-line"><Bell size={14}/> VOICE <b>DEMO MODE</b></span><div className="notify-buttons"><button className="button secondary" onClick={()=>setNotice("SMS demo queued — no message sent.")}>SEND TEST SMS</button><button className="button secondary" onClick={()=>setNotice("Voice demo queued — no call placed.")}>PLACE TEST CALL</button></div></div></section>
    </main><footer><div className="footer-brand"><img src="/manus-storage/lews-logo_09575f20.png" alt=""/><strong>LEWS</strong><span>LANDSLIDE EARLY WARNING SYSTEM</span></div><div>REAL SYSTEM BEHAVIOR — SIMULATED SENSOR INPUTS</div><b>SIMULATION ONLY — NOT FOR OPERATIONAL USE</b></footer>{notice&&<div className="toast"><Check size={15}/>{notice}<button onClick={()=>setNotice(null)}><X size={14}/></button></div>}
  </div>
}
function Metric({icon,label,value,unit,prev,color}:{icon:React.ReactNode;label:string;value:string;unit:string;prev:number;color:string}){ const v=Number(value); return <div className="metric"><div className="metric-label">{icon}{label}</div><div className="metric-value" style={{color}}>{value}<small>{unit}</small></div><div className="metric-delta"><ArrowUpRight size={13}/> {delta(v,prev)}</div></div> }
