/* Tectonic Signal OS: premium climate-tech SaaS, precise telemetry, breathable product storytelling. */
import { useMemo, useState } from "react";
import { Activity, ArrowRight, BellRing, Check, ChevronDown, CircleHelp, CloudRain, Database, ExternalLink, Gauge, Layers3, Menu, Radio, ShieldCheck, SlidersHorizontal, Sparkles, X, Zap } from "lucide-react";
import { ManusDialog } from "@/components/ManusDialog";

type Tier = "STABLE" | "WATCH" | "CRITICAL";
type Zone = { id:string; name:string; region:string; tier:Tier; score:number; delta:string; rainfall:string; soil:string; tilt:string; note:string; color:string };

const zones:Zone[] = [
  {id:"KDG-03",name:"Kodagu",region:"Western Ghats",tier:"WATCH",score:73,delta:"+8.4",rainfall:"18.4 mm/hr",soil:"78.2%",tilt:"0.084°/hr",note:"Soil moisture is approaching saturation for this zone.",color:"#D6A24E"},
  {id:"CHK-01",name:"Chikkamagaluru",region:"Western Ghats",tier:"WATCH",score:64,delta:"+4.1",rainfall:"12.8 mm/hr",soil:"57.4%",tilt:"0.062°/hr",note:"Rainfall intensity is currently the strongest contributor.",color:"#D6A24E"},
  {id:"DJE-06",name:"Darjeeling",region:"Eastern Himalayas",tier:"WATCH",score:57,delta:"+2.8",rainfall:"13.5 mm/hr",soil:"61.7%",tilt:"0.101°/hr",note:"Slope tilt is increasing above the local baseline.",color:"#D6A24E"},
  {id:"WYD-04",name:"Wayanad",region:"Western Ghats",tier:"STABLE",score:38,delta:"−1.3",rainfall:"15.1 mm/hr",soil:"71.4%",tilt:"0.068°/hr",note:"Conditions remain within the current monitoring baseline.",color:"#7DE2D1"},
  {id:"NLG-05",name:"Nilgiris",region:"Tamil Nadu",tier:"STABLE",score:32,delta:"−0.8",rainfall:"11.2 mm/hr",soil:"53.6%",tilt:"0.092°/hr",note:"Conditions remain within the current monitoring baseline.",color:"#7DE2D1"},
  {id:"UKA-02",name:"Uttara Kannada",region:"Western Ghats",tier:"CRITICAL",score:86,delta:"+12.2",rainfall:"23.8 mm/hr",soil:"84.1%",tilt:"0.117°/hr",note:"Critical conditions detected. Authority attention recommended.",color:"#F0796B"},
];

const tierColor = (tier:Tier) => tier === "CRITICAL" ? "#F0796B" : tier === "WATCH" ? "#D6A24E" : "#7DE2D1";
const faqs = [
  ["What does LEWS actually monitor?", "LEWS combines rainfall, soil moisture, and slope-tilt signals into a transparent risk score for a defined hillside or village. The product preview uses simulated sensor inputs so the warning logic can be inspected safely."],
  ["Can this replace a regional forecast?", "No. LEWS is designed as a hyperlocal last-mile layer that can complement regional forecasting and district bulletins. It narrows attention to the zones where local conditions are changing."],
  ["How does the score stay explainable?", "Every score exposes its strongest contributing signal, the current reading, the recent delta, and the exact zone state. Operators can open the evidence trail instead of trusting a black-box status."],
  ["What happens when a threshold is crossed?", "The prototype records the transition, changes the response state, and prepares a notification action. Demo SMS and call actions are clearly labeled as simulated and do not contact real recipients."],
];

function PreviewChart({critical=false}:{critical?:boolean}) { return <svg className="preview-chart" viewBox="0 0 360 130" preserveAspectRatio="none" aria-label="Risk score trend preview"><defs><linearGradient id={critical?"fill-critical":"fill-watch"} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor={critical?"#F0796B":"#7DE2D1"} stopOpacity=".28"/><stop offset="1" stopColor={critical?"#F0796B":"#7DE2D1"} stopOpacity="0"/></linearGradient></defs><path d="M0 105 C32 102,42 92,68 96 S102 86,126 90 S160 74,186 79 S225 54,250 64 S286 45,310 51 S340 34,360 39 V130 H0Z" fill={`url(#${critical?"fill-critical":"fill-watch"})`}/><path d="M0 105 C32 102,42 92,68 96 S102 86,126 90 S160 74,186 79 S225 54,250 64 S286 45,310 51 S340 34,360 39" fill="none" stroke={critical?"#F0796B":"#7DE2D1"} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/></svg> }

export default function Home() {
  const [filter,setFilter] = useState<"ALL"|Tier>("ALL");
  const [selected,setSelected] = useState<Zone>(zones[0]);
  const [drawerOpen,setDrawerOpen] = useState(false);
  const [faqOpen,setFaqOpen] = useState(0);
  const [notice,setNotice] = useState<string | null>(null);
  const visibleZones = useMemo(()=>filter === "ALL" ? zones : zones.filter(z=>z.tier===filter),[filter]);
  const openZone=(zone:Zone)=>{setSelected(zone);setDrawerOpen(true)};
  const demo=(kind:"SMS"|"CALL")=>setNotice(kind === "SMS" ? "Demo SMS sent — no real message delivered." : "Demo call made — no real call placed.");

  return <div className="site-shell">
    <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <header className="site-nav"><a className="brand-lockup" href="#top"><span className="brand-mark"><span/><span/><span/></span><span><strong>LEWS</strong><small>SIGNAL OS</small></span></a><nav><a href="#platform">Platform</a><a href="#signals">Signals</a><a href="#faq">FAQ</a></nav><div className="nav-actions"><span className="nav-status"><i/> NETWORK ONLINE</span><a className="nav-link" href="#platform">Open console <ArrowRight size={14}/></a><button className="mobile-menu" aria-label="Open navigation"><Menu size={18}/></button></div></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><div className="kicker"><span className="kicker-line"/> HYPERLOCAL RISK INTELLIGENCE</div><h1>See the signal<br/><em>before</em> it becomes a bulletin.</h1><p className="hero-lead">LEWS turns fragmented slope measurements into a calm, explainable operating picture for the people who need to decide what happens next.</p><div className="hero-actions"><a className="cta cta-primary" href="#platform">Explore the platform <ArrowRight size={17}/></a><button className="cta cta-secondary" onClick={()=>openZone(zones[0])}>Open evidence trail <ExternalLink size={16}/></button></div><div className="hero-proof"><span><Check size={14}/> Transparent scoring</span><span><Check size={14}/> Last-mile ready</span><span><Check size={14}/> Simulation-safe</span></div></div><div className="hero-preview"><div className="preview-orbit orbit-a"/><div className="preview-orbit orbit-b"/><div className="preview-window"><div className="preview-top"><span className="window-dots"><i/><i/><i/></span><span className="preview-path">LEWS / LIVE CONSOLE</span><span className="preview-live"><i/> LIVE</span></div><div className="preview-body"><div className="preview-heading"><div><span className="mini-label">CURRENT NETWORK STATE</span><h3>Decision surface</h3></div><span className="preview-date">08:42:16 UTC</span></div><div className="preview-metrics"><div><span>ACTIVE ZONES</span><strong>06</strong><small>+02 this week</small></div><div><span>NETWORK HEALTH</span><strong>98.4<small>%</small></strong><small className="cyan">within baseline</small></div><div><span>MAX SIGNAL</span><strong className="ochre">73</strong><small>WATCH / KDG-03</small></div></div><div className="preview-chart-wrap"><div className="chart-header"><span>RISK SIGNAL / 24H</span><span className="chart-legend"><i/> CURRENT <b>+8.4</b></span></div><PreviewChart/></div><div className="preview-foot"><span><Radio size={13}/> SENSOR STREAM / SIMULATED</span><span><ShieldCheck size={13}/> EVIDENCE READY</span></div></div></div><div className="floating-chip chip-top"><span className="chip-pulse"/> Alert logic <b>explainable</b></div><div className="floating-chip chip-bottom"><Activity size={13}/> Drift detected <b>+8.4</b></div></div></section>
      <section className="logo-strip"><span>Built for teams working between signal and action</span><div><b>FIELD OPS</b><b>RESEARCH LABS</b><b>PUBLIC SAFETY</b><b>CLIMATE PROGRAMS</b></div></section>
      <section id="platform" className="platform-section section-wrap"><div className="section-intro"><div><div className="kicker"><span className="kicker-line"/> THE OPERATING LAYER / 01</div><h2>A clearer surface<br/>for <em>messy terrain.</em></h2></div><p>Designed for teams who need the full chain in view: a live measurement, a reason to care, and a next action that does not hide behind a dashboard maze.</p></div><div className="feature-grid"><article className="feature-card feature-large"><div className="feature-index">01 / SIGNAL GRAPH</div><div className="feature-icon"><Activity size={18}/></div><h3>Risk, with its receipts.</h3><p>Trace every score back to rainfall, moisture, and tilt. Compare the current state to a local baseline before escalating attention.</p><button className="text-button" onClick={()=>openZone(zones[0])}>Inspect a zone <ArrowRight size={15}/></button><div className="mini-graph"><div className="mini-graph-label"><span>RISK SCORE</span><strong>73 <small>/ 100</small></strong></div><PreviewChart/></div></article><article className="feature-card"><div className="feature-index">02 / RESPONSE STATE</div><div className="feature-icon icon-ochre"><BellRing size={18}/></div><h3>From signal to stance.</h3><p>Watch, stable, and critical are not just colors. Each state carries a clear operating posture for the next person in the chain.</p><div className="state-stack"><span><i className="dot cyan-dot"/> STABLE <b>observe</b></span><span><i className="dot ochre-dot"/> WATCH <b>prepare</b></span><span><i className="dot red-dot"/> CRITICAL <b>respond</b></span></div></article><article className="feature-card"><div className="feature-index">03 / DATA LINEAGE</div><div className="feature-icon icon-blue"><Database size={18}/></div><h3>Evidence stays close.</h3><p>Keep timestamp, source, confidence, and sensor context beside the alert so the story survives handoffs and reviews.</p><div className="lineage"><span>INPUTS <b>12</b></span><span>RULES <b>04</b></span><span>OUTPUTS <b>06</b></span></div></article></div></section>
      <section id="signals" className="signals-section section-wrap"><div className="section-intro signals-intro"><div><div className="kicker"><span className="kicker-line"/> LIVE SIGNALS / 02</div><h2>Stay close to<br/><em>the changing ground.</em></h2></div><div className="intro-side"><p>Filter the network by response state, then open any zone to read the evidence behind its score.</p><a className="text-button" href="#faq">How it works <ArrowRight size={15}/></a></div></div><div className="signal-toolbar"><div className="filter-group"><SlidersHorizontal size={15}/><span>SHOW</span>{(["ALL","WATCH","STABLE","CRITICAL"] as const).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}<small>{item==="ALL"?zones.length:zones.filter(z=>z.tier===item).length}</small></button>)}</div><span className="network-readout"><i/> 06 NODES REPORTING / UPDATED JUST NOW</span></div><div className="signal-grid">{visibleZones.map(zone=><button className="signal-card" key={zone.id} onClick={()=>openZone(zone)}><div className="signal-card-head"><span className="signal-tier" style={{color:tierColor(zone.tier)}}><i style={{background:tierColor(zone.tier)}}/> {zone.tier}</span><span className="signal-id">{zone.id} <ArrowRight size={14}/></span></div><div className="signal-card-main"><div><h3>{zone.name}</h3><p>{zone.region}</p></div><strong style={{color:tierColor(zone.tier)}}>{zone.score}<small>/100</small></strong></div><div className="signal-card-meta"><span>Δ {zone.delta}</span><span>{zone.rainfall}</span><span>{zone.tilt}</span></div><div className="signal-bar"><i style={{width:`${zone.score}%`,background:tierColor(zone.tier)}}/></div><div className="signal-card-footer"><span>{zone.note}</span><ExternalLink size={14}/></div></button>)}</div></section>
      <section className="proof-section"><div className="proof-card"><div className="proof-copy"><div className="kicker"><span className="kicker-line"/> A PRODUCT SURFACE, NOT A BLACK BOX / 03</div><h2>Every alert should<br/><em>earn attention.</em></h2><p>LEWS is built around a simple promise: an operator can see what changed, understand why it matters, and hand the context to the next person without rewriting the story.</p><button className="cta cta-primary" onClick={()=>openZone(zones[5])}>Open a live evidence trail <ArrowRight size={16}/></button></div><div className="proof-console"><div className="console-label"><span><Zap size={14}/> DECISION TRACE</span><span>NODE / UKA-02</span></div><div className="console-score"><div><small>RISK SCORE</small><strong>86</strong></div><span className="critical-tag">CRITICAL</span></div><div className="console-reason"><span>STRONGEST CONTRIBUTOR</span><strong>Soil moisture</strong><p>84.1% is 19.2 points above local baseline.</p></div><div className="console-row"><span><CloudRain size={14}/> RAINFALL</span><b>23.8 mm/hr</b></div><div className="console-row"><span><Gauge size={14}/> SLOPE TILT</span><b>0.117°/hr</b></div><div className="console-row"><span><Layers3 size={14}/> CONFIDENCE</span><b className="cyan">94.2%</b></div><div className="console-foot"><span>LAST CHECK / 08:42:16</span><span><i/> EVIDENCE READY</span></div></div></div></section>
      <section id="faq" className="faq-section section-wrap"><div className="faq-heading"><div className="kicker"><span className="kicker-line"/> QUESTIONS WE KEEP OPEN / 04</div><h2>Clarity is part<br/>of the <em>product.</em></h2><p>Short answers for teams evaluating a hyperlocal warning layer.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-item ${faqOpen===i?"open":""}`} key={q}><button onClick={()=>setFaqOpen(faqOpen===i?-1:i)}><span>{String(i+1).padStart(2,"0")}</span><strong>{q}</strong><ChevronDown size={18}/></button>{faqOpen===i&&<div className="faq-answer"><p>{a}</p></div>}</div>)}</div></section>
      <section className="final-cta"><div className="final-cta-inner"><div><div className="kicker"><span className="kicker-line"/> READY WHEN THE GROUND MOVES</div><h2>Make the next signal<br/><em>easier to act on.</em></h2></div><div className="final-actions"><button className="cta cta-primary" onClick={()=>openZone(zones[0])}>Explore the console <ArrowRight size={16}/></button><button className="cta cta-secondary" onClick={()=>setNotice("Demo workspace request noted — no account was created.")}>Request a demo <ArrowRight size={16}/></button></div></div></section>
    </main>
    <footer className="site-footer"><a className="brand-lockup" href="#top"><span className="brand-mark"><span/><span/><span/></span><span><strong>LEWS</strong><small>SIGNAL OS</small></span></a><span>Hyperlocal risk intelligence / transparent by design</span><span className="footer-right">SIMULATION MODE <i/></span></footer>
    <ManusDialog open={drawerOpen} onOpenChange={setDrawerOpen} onLogin={()=>setNotice("Demo workspace access noted — no account was created.")} title={`${selected.name} / ${selected.id}`} description="Evidence trail · simulated field node" actionLabel="Acknowledge demo state" logo="/manus-storage/lews-logo_09575f20.png"><div className="drawer-content"><div className="drawer-score"><span style={{color:tierColor(selected.tier)}}><i/> {selected.tier}</span><strong>{selected.score}<small>/100</small></strong></div><p className="drawer-note">{selected.note}</p><div className="drawer-metrics"><span><small>RAINFALL</small><b>{selected.rainfall}</b></span><span><small>SOIL MOISTURE</small><b>{selected.soil}</b></span><span><small>SLOPE TILT</small><b>{selected.tilt}</b></span></div><div className="drawer-lineage"><span><Database size={14}/> SOURCE / SIMULATED SENSOR STREAM</span><span><Check size={14}/> SCORE / EXPLAINABLE RULE SET</span><span><ShieldCheck size={14}/> STATE / OPERATOR REVIEW READY</span></div><div className="drawer-actions"><button className="cta cta-secondary" onClick={()=>demo("SMS")}>Send demo SMS <ArrowRight size={14}/></button><button className="cta cta-secondary" onClick={()=>demo("CALL")}>Place demo call <ArrowRight size={14}/></button></div></div></ManusDialog>
    {notice&&<div className="toast"><Check size={15}/><span>{notice}</span><button onClick={()=>setNotice(null)} aria-label="Dismiss message"><X size={14}/></button></div>}
  </div>;
}
